### ISSUE TITLE
question

### ISSUE THREAD

**Issue by haer0248** [GoogleX133/WebConsole#1]
Excuse me, the "webserver.zip" is https://github.com/SuperPykkon/minecraft-server-web-console right?

**Comment by BroNils** [comment]
yep, i just made the server-side/internal program to the UI of SuperPykkon

**Comment by BroNils** [comment]
this is my first mc plugin project, i don't have much documentation of minecraft 1.8-1.12 . and this project is unmaintained, sorry :(
